apiVersion: apps/v1
kind: Deployment
metadata:
  
  labels:
    run: event-backend
  name: event-backend
 
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: event-backend
  
  template:
    metadata:
     
      labels:
        run: event-backend
    spec:
      containers:
      - name: event-backend
        image: event/backend:latest
        imagePullPolicy: Never
        ports:
          - name: http
            containerPort: 8081 # The port that the container exposes
        resources:
          limits:
            cpu: "0.5"
            memory: "500Mi"
        envFrom:
          - secretRef:
              name: appli-secret-pub
---
apiVersion: v1
kind: Service
metadata:
  
  labels:
    run: event-backend
  name: event-backend
  
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    run: event-backend
  type: ClusterIP
