apiVersion: apps/v1
kind: Deployment
metadata:
  
  generation: 1
  labels:
    run: app-nginx
  name: app-nginx
 
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: app-nginx
  
  template:
    metadata:
     
      labels:
        run: app-nginx
    spec:
      volumes:
      - name:  conf-nginx
        hostPath:
          path: /d/tmp/backend-event/volumes/conf
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: app-nginx
        volumeMounts:
          - mountPath: "/etc/nginx/conf.d"
            name: conf-nginx
        
---
apiVersion: v1
kind: Service
metadata:
  
  labels:
    run: app-nginx
  name: app-nginx
  
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30200
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: app-nginx
  type: LoadBalancer
