apiVersion: v1
kind: PersistentVolume
metadata:
  name:  backend-event-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path:  /d/tmp/backend-event/volumes/logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-event-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"
