#keycloak:
#    auth-server-url: http://localhost:8088/auth
#    credentials:
#        secret: 91032c16-8571-4513-86c5-84ccd3824a81
#    realm: lmsys-realm
#    resource: event-backend
#    security-constraints:
#    -   authRoles:
#        - USER
#        securityCollections:
#        -   patterns:
#            - /api/events/*
#    -   authRoles:
#        - ADMIN
#        securityCollections:
#        -   patterns:
#            - /api/user/*
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: prometheus,health
server:
    port: 8081
    servlet:
        contextPath: /event-backend
spring:
    jackson:
        serialization:
            INDENT_OUTPUT: true
    mail:
        host: ${mail.host}
        password: ${mail.password}
        port: ${mail.port}
        properties:
            mail:
                smtp:
                    auth: true
                    connectiontimeout: 5000
                    starttls:
                        enable: false
                    timeout: 3000
                    writetimeout: 5000
        username: ${mail.from}
    profiles:
        active: local
    servlet:
        multipart:
            max-file-size: 500KB
            max-request-size: 500KB
#resource server     
security:
    oauth2:
        resource:
            id: event-backend
            jwt:
                key-value: ${key.cloak.value}
            token-info-uri: ${rest.security.issuer-uri}/protocol/openid-connect/token/introspect
            user-info-uri: ${rest.security.issuer-uri}/protocol/openid-connect/userinfo
        client:
            access-token-uri: ${rest.security.issuer-uri}/protocol/openid-connect/token
            user-authorization-uri: ${rest.security.issuer-uri}/protocol/openid-connect/auth
            client-id: event-backend
            client-secret: 91032c16-8571-4513-86c5-84ccd3824a81
            grant-type: client_credentials
            scope: openid
