spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: ${SPRING_DATASOURCE_PASSWORD}
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
          ddl-auto: update
rest:
    security:
        issuer-uri: ${ISSUER_URI}/${REALM_NAME}
        enabled: true
        api-matcher: /api/**
        cors:
            allowed-headers: '*'
            allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
            allowed-origins: '*'
            max-age: 3600