spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: kiram
        url: jdbc:mysql://localhost:3306/bmnsys?verifyServerCertificate=false&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
          ddl-auto: update
