logging:
    file: d:/tmp/testFile.log
spring:
    jpa:
        hibernate:
          ddl-auto: update
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
        username: sa
    h2:
        console:
            enabled: true
            path: /h2-console
rest:
    security:
        issuer-uri: http://localhost:8088/auth/realms/lmsys-realm
        enabled: true
        api-matcher: /api/**
        cors:
            allowed-headers: '*'
            allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
            allowed-origins: '*'
            max-age: 3600
