apiVersion: apps/v1
kind: Deployment
metadata:
  
  labels:
    run: event-backend
  name: event-backend
 
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: event-backend
  
  template:
    metadata:
     
      labels:
        run: event-backend
    spec:
      containers:
      - name: event-backend
        image: event/backend:v4
        imagePullPolicy: Never
        ports:
          - name: http
            containerPort: 8081 # The port that the container exposes
        resources:
          limits:
            cpu: 1
            memory: "1Gi"
        envFrom:
          - secretRef:
              name: appli-secret-pub
---
apiVersion: v1
kind: Service
metadata:
  
  labels:
    run: event-backend
  name: event-backend
  
spec:
  clusterIP: 10.110.0.119
  externalIPs:
  - 192.168.1.10
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30290
    port: 9000
    protocol: TCP
    targetPort: 8081
  selector:
    run: event-backend
  sessionAffinity: None
  type: NodePort
